### ISSUE TITLE
Removing "I" header from Module interface

### ISSUE THREAD

**Issue by yandhi** [Ingros/ingrosware#1]
Whats up guys haha!

y'all probably thought I died or something, but I got bored and came here to see whats up.

For your IModule class, the "I" header is irrelevant in the naming convention. You don't have a class named "Module", so rather than "IModule", I personally would just use Module. Also, you could create an abstract layer in between the Module class and your subtypes. This would probably minimize a good bit of boilerplate code that you guys had to repeat over for each type. Instead, these types could have a superclass that contains common fields and values then you don't have to rewrite the same code over and over again.

If you got any questions, y'all got my snap / # so message me there.

**Comment by dashnullify** [comment]
Ya I get that I will get right on that!

**Comment by dashnullify** [comment]
Finished in latest commit  
https://github.com/Ingros/ingrosware/commit/d4553d0b2b7a22a28d653722ce520af3027baad6
