### ISSUE TITLE
Game Crash Upon Joining World / Server

### ISSUE THREAD

**Issue by crematoriums** [Ingros/ingrosware#10]
It should be installed correctly, and here is the error:

The game crashed whilst ticking entity
Error: java.lang.NoSuchMethodError: net.minecraft.client.entity.EntityPlayerSP.getRotationYaw()F

**Comment by alerithe** [comment]
This issue *should* have been fixed yesterday if I recall correctly, is it crashing because of that when you launch through the developer environment or through normal Minecraft Forge?
