### ISSUE TITLE
niggafart

### ISSUE THREAD

**Issue by wuaDev** [Ingros/ingrosware#2]
HUGE best client

taps imp👍👍👌👌

10/5 would recommend

**Comment by dashnullify** [comment]
dont open unneeded issues.

**Comment by wuaDev** [comment]
you told me not to open it again so i did it :dab:

**Comment by wuaDev** [comment]
nvm i didnt i have no idea how github works lmao

**Comment by oHare2** [comment]
shut up

**Comment by dashnullify** [comment]
bruh
