### ISSUE TITLE
Add linux support

### ISSUE THREAD

**Issue by Sleeving** [Ingros/ingrosware#8]
Add linux support monkeys :wheelchair:

**Comment by dashnullify** [comment]
bruh what

**Comment by Sleeving** [comment]
it crashes on linux becuase the config folder doesnt support the linux file system

**Comment by dashnullify** [comment]
lol what? it creates a file in da mc folder lol?

**Comment by Sleeving** [comment]
?
Last time I used it, it put a config folder in c:\users\user\ingrosware

**Comment by dashnullify** [comment]
idk if you cant read or something but 
https://github.com/Ingros/ingrosware/blob/master/src/main/java/best/reich/ingrosware/IngrosWare.java#L53

**Comment by dashnullify** [comment]
Send crash log lol? its been crashing for rotationYaw in entityplayer so im currently fixing that i doubt it has todo with using linux lol?

**Comment by NirvanaNevermind** [comment]
no it's an issue with discord rpc, i removed it and it started working.

**Comment by dashnullify** [comment]
ohhhhh ok
